### PR TITLE
Fix broken link "Using simple-check with Expectations"

### PR DESCRIPTION
**Pull request by maio**

### CODE REVIEW

**Comment by gfredericks** [comment]
As per [CONTRIBUTING](https://github.com/clojure/test.check/blob/master/CONTRIBUTING.md) this project does not accept pull requests, but I have made the fix on master. Thanks!

**Comment by harrigan** [comment]
This link is broken again.

**Comment by seancorfield** [comment]
Looks like all of that site's content is gone (curtis.io) so I guess the link might just as well be deleted?

**Comment by gfredericks** [comment]
I poked him on twitter, I'll delete the link if that doesn't go anywhere.

**Comment by gfredericks** [comment]
I removed it

**Pull request closed without merging**
